name: CI

on:
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v19.0.1+4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          # vercel-args: --prod
          # working-directory: ./
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-name: ${{ secrets.VERCEL_PROJECT_NAME }}
          scope: ${{ secrets.VERCEL_SCOPE }}
        id: deploy-to-vercel

      - name: Comment Deploy Preview on PR
        uses: jungwinter/comment@v1
        id: create
        with:
          type: create
          body: |
            ### Preview Deploy Ready!

            ### [${{ steps.deploy-to-vercel.outputs.preview-url }}](${{ steps.deploy-to-vercel.outputs.preview-url }})

            ### 🚀
          issue_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
