name: CI/CD

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy www/public to Vercel
        uses: amondnet/vercel-action@v19.0.1+3
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: --prod
          working-directory: /
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-name: ${{ secrets.VERCEL_PROJECT_NAME }}
          scope: ${{ secrets.VERCEL_SCOPE }}
